version: '3'
services:
  transport:
    image: 'rabbitmq:management'
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server'
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Docker@123
    ports:
      - "1433:1433"
  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: Docker123
      ports:
        - 27017:27017
  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: Docker123
      depends_on:
        - mongo